version: '3'

services:
  server:
    image: nginx:alpine
    restart: always
    depends_on:
      - web
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - public:/code/public 

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes: 
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      
  web:
    image: xwisert/richfamily:updated
    command: bash -c "/code/run.sh"
    restart: always
    env_file:
      - .env
    depends_on:
      - app_database
    volumes:
      - public:/code/public

  app_database:
    image: postgres:14
    env_file:
      - .env
    volumes:
      - app_data:/var/lib/pgsql/data
    restart: always
    ports:
      - '5432:5432'

volumes: 
  app_data:
  public:

